# Site settings
title: Your Blog's Title
email: your-email@example.com
description: >- # This means to ignore newlines until the closing indicator
  Write a short description of your blog here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://[username].github.io" # the base hostname & protocol for your site
timezone: UTC

# Build settings
markdown: kramdown
theme: minima # or any other theme you're using
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# Include any files you want to include in your site build
# even if they are typically excluded by Jekyll (e.g. dotfiles)
include:
  - ".well-known"

# If you're using other plugins, you might need more configurations here.

# Kramdown settings (for markdown processing with LaTeX support via MathJax)
kramdown:
  input: GFM # GitHub Flavored Markdown
  math_engine: mathjax
